site_name: Site3

# Repository - Uncommentd link to not show it
repo_url: https://github.com/surgocode/Docs-MKDocs-Demo-Monorepo
repo_name: surgocode/Docs-MKDocs-Demo-Monorepo
edit_uri: edit/main

docs_dir: ./docs
